In [77]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import cross_validation

In [78]:
data = pd.read_csv("tic-tac-toe.data", header=None)

In [79]:
data.head()

   0  1  2  3  4  5  6  7  8         9
0  x  x  x  x  o  o  x  o  o  positive
1  x  x  x  x  o  o  o  x  o  positive
2  x  x  x  x  o  o  o  o  x  positive
3  x  x  x  x  o  o  o  b  b  positive
4  x  x  x  x  o  o  b  o  b  positive

In [80]:
#Convertiremos los datos categoricos a numericos X 2 = x, 1 = o y 0 = b. Y Positive = 1, Negative = 0
funcion = preprocessing.LabelEncoder()
for f in data:
    data[f]=funcion.fit_transform(data[f])
data.head()

   0  1  2  3  4  5  6  7  8  9
0  2  2  2  2  1  1  2  1  1  1
1  2  2  2  2  1  1  1  2  1  1
2  2  2  2  2  1  1  1  1  2  1
3  2  2  2  2  1  1  1  0  0  1
4  2  2  2  2  1  1  0  1  0  1

In [81]:
# Separamos los X y Y de los datos
y = data.pop(9)
X = data

In [82]:
# Fragmentamos los datos
X_train, X_test,y_train,y_test = train_test_split(X,y, 
                                                 test_size=0.3,
                                                 random_state = 0)

In [83]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.svm import SVR

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import explained_variance_score

In [84]:
models = []
models.append(("Linear Regression",LinearRegression()))
models.append(("Random Forest Regressor",RandomForestRegressor()))
models.append(("Decision Tree Regressor",DecisionTreeRegressor()))
models.append(("KNeighbors Regressor",KNeighborsRegressor()))
models.append(("Extra Trees Regressor",ExtraTreesRegressor()))
models.append(("SVR",SVR()))

In [86]:
for name, model in models:
        
    model.fit(X_train,y_train)
    score_test = model.score(X_test, y_test)
    
    prediccion = model.predict(X)
    score = explained_variance_score(Y,prediccion)
    error = mean_absolute_error(prediccion, Y)
    
    print("Modelo %s: \n Test Score: %f \n Score: %f \n Error: %f"% (name,score_test,score,error) )

Modelo Linear Regression:
 Test Score: 0.021380
 Score: 0.058816
 Error: 0.423780
Modelo Random Forest Regressor:
 Test Score: 0.832868
 Score: 0.924055
 Error: 0.065762
Modelo Decision Tree Regressor:
 Test Score: 0.754894
 Score: 0.926421
 Error: 0.016701
Modelo KNeighbors Regressor:
 Test Score: 0.415421
 Score: 0.514665
 Error: 0.216284
Modelo Extra Trees Regressor:
 Test Score: 0.805294
 Score: 0.941479
 Error: 0.035386
Modelo SVR:
 Test Score: 0.642878
 Score: 0.751079
 Error: 0.181917